/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for opening a database. */
export interface OpenOptions {
  /** Page size in bytes (default: 4096). */
  pageSize?: number
  /** Number of pages in the buffer pool cache (default: 256). */
  cacheCapacity?: number
}
/** Open a CypherLite database at the given path. */
export declare function open(path: string, options?: OpenOptions | undefined | null): Database
/** Return the library version string. */
export declare function version(): string
/** Return a comma-separated string of compiled feature flags. */
export declare function features(): string
/** The main CypherLite database handle for Node.js. */
export declare class Database {
  /**
   * Execute a Cypher query string.
   *
   * Optional second argument provides named parameters as a plain object.
   */
  execute(query: string, params?: object | undefined | null): CylResult
  /** Close the database. Safe to call multiple times. */
  close(): void
  /** Check if the database is closed. */
  get isClosed(): boolean
  /** Begin a new transaction. */
  begin(): Transaction
}
/**
 * A query result containing columns and rows.
 *
 * Row data is stored as Rust types and converted to JS on access.
 */
export declare class CylResult {
  /** Column names as an array of strings. */
  get columns(): Array<string>
  /** Number of rows in the result. */
  get length(): number
  /** Get a single row by index as a plain JS object. */
  row(index: number): object
  /** Convert all rows to an array of plain JS objects. */
  toArray(): Array<object>
}
/**
 * A transaction wrapping CypherLite execute calls.
 *
 * Shares the database Mutex with the parent Database object.
 */
export declare class Transaction {
  /** Execute a Cypher query within this transaction. */
  execute(query: string, params?: object | undefined | null): CylResult
  /** Commit the transaction. */
  commit(): void
  /** Rollback the transaction (Phase 2: no-op at storage level). */
  rollback(): void
}
