// Augmented type definitions for CypherLite Node.js bindings.
// index.d.ts is auto-generated by napi-rs on each build;
// this file adds the Symbol.iterator type applied at runtime by lib.js.

export * from './index.js';

declare module './index.js' {
  interface CylResult extends Iterable<Record<string, any>> {
    [Symbol.iterator](): Iterator<Record<string, any>>;
  }
}
