'use strict';

// Wrapper around the napi-rs auto-generated index.js entry point.
// index.js is regenerated by `napi build --platform` and cannot be
// modified directly. This file patches runtime behavior (Symbol.iterator)
// and serves as the package entry point ("main" in package.json).
// CJS is required here because index.js is CommonJS.

const binding = require('./index.js');

// Add Symbol.iterator to CylResult so for...of, spread, and
// Array.from work on query results.
binding.CylResult.prototype[Symbol.iterator] = function* () {
  for (let i = 0; i < this.length; i++) {
    yield this.row(i);
  }
};

module.exports = binding;
